-added simple ether address check (WIK)
Neufund/dapp-starter-kit pull request #12
Opened 2017-05-31 14:40 UTC by Moejoe90

Simple components or util's like this would you put them all in a general util file or specify them as components ?

2017-05-31 14:55 UTC, Recmo commented
This is not a React component but just a utility function. As such, it should start with a lowercase letter (only components and classes start with uppercase) and it should not have `propTypes` (which is also only for components.

I suggest we create a file `/src/ether-utils.js` similar to the `src/utils.js` that is already there.

2017-05-31 14:57 UTC, recmo requested changes

2017-05-31 14:57 UTC, Recmo commented on src/components/EtherAddress.js
> +const EtherAddress = address => isValidAddress(address);
This does not return Html (but boolean) so it is not a React component but a regular function.

2017-06-01 14:07 UTC, Moejoe90 commented
I fixed the comments waiting for confirmation

2017-06-01 14:30 UTC, recmo approved these changes
Let's merge it as is and revisit later.

2017-06-01 14:30 UTC, Recmo commented on src/ether-utils.js
> +const EtherAddress = address => isValidAddress(address);
This is a regular function, not a component, so by convention it should start with a lowecase letter.

2017-06-01 14:30 UTC, Recmo commented on src/ether-utils.js
> +export default EtherAddress;
We want to add multiple functions to this file, so there is not a function that would obviously be default.

2017-06-01 14:30 UTC, Recmo commented on src/ether-utils.js
> +const EtherAddress = address => isValidAddress(address);
The function name doesn't describe it's purpose. Something like `checkAddress`, `verifyAddress`, `validateAddress`, etc, would work.

2017-06-01 14:30 UTC, merged

2017-06-01 14:40 UTC, Moejoe90 commented
I fixed these changes do we make a new pr for them, or just keep for now?

2017-06-01 15:15 UTC, Moejoe90 commented on src/ether-utils.js
> +export default EtherAddress;
Es lint gives this error then 
4:1  error  Prefer default export  import/prefer-default-export
and the commit fails unless we put it in eslint ignore

2017-06-01 15:33 UTC, Moejoe90 commented on src/ether-utils.js
> +const EtherAddress = address => isValidAddress(address);
I chose verifyAddress