Add notes on how to use Webstorm for dev
Neufund/dapp-starter-kit pull request #5
Opened 2017-05-22 15:54 UTC by banciur

2017-05-22 16:01 UTC, Moejoe90 approved these changes

2017-05-22 16:03 UTC, Moejoe90 approved these changes
I just emphasize on Airbnb rules to be set as an option if its not a default

2017-05-30 14:50 UTC, recmo requested changes
Great additions! There are some minor typos.

2017-05-30 14:50 UTC, Recmo commented on README.md
> +You need to create branch that tracks this repository and rebase it on your master. Then when there will be never versions of starter kit (new features, bugfixes etc) you can pull those using starter
`never` → `newer`

2017-05-30 14:50 UTC, Recmo commented on README.md
> +Lets assume you created ```new_project``` use following commands to setup it:
`use following` → `use the following`

2017-05-30 14:50 UTC, Recmo commented on README.md
> +ignore msg "Your branch is based on 'origin/master', but the upstream is gone." - it's beacuse your master is empty thanks to usage of "--allow-empty" parameter
`Ignore the message`

2017-05-31 14:52 UTC, recmo approved these changes

2017-05-31 17:05 UTC, merged